export const CATEGORIES: string[] = [
    "Farmer", 
    "Student", 
    "NGO Worker", 
    "Artisan", 
    "Teacher", 
    "Fisherman", 
    "Small Business Owner", 
    "Craftsman", 
    "Homemaker", 
    "Engineer", 
    "Doctor", 
    "Nurse", 
    "Social Worker", 
    "Entrepreneur", 
    "Tailor", 
    "Blacksmith", 
    "Tour Guide", 
    "Photographer", 
    "Software Developer", 
    "Content Writer",
    "Electrician",
  ];
  