export const communitySkills: string[] = [
    "Agriculture", 
    "Fishing", 
    "Animal Husbandry", 
    "Carpentry", 
    "Plumbing", 
    "Masonry", 
    "Cooking", 
    "Baking", 
    "Sewing", 
    "Knitting", 
    "Herbal Medicine", 
    "First Aid", 
    "Animal Care", 
    "Blacksmithing", 
    "Pottery", 
    "Leatherworking", 
    "Woodworking", 
    "Tailoring", 
    "Basket Weaving", 
    "Beekeeping", 
    "Farming", 
    "Candle Making", 
    "Traditional Storytelling", 
    "Lumberjacking", 
    "Canning and Preserving", 
    "Hunting", 
    "Dyeing Fabric", 
    "Firewood Cutting", 
    "Soap Making", 
    "Oral History", 
    "Metalworking", 
    "Farming Techniques", 
    "Bird Watching", 
    "Vermiculture", 
    "Community Organizing", 
    "Construction", 
    "Sustainable Practices", 
    "Water Conservation", 
    "Renewable Energy Use", 
    "Recycling", 
    "Childcare", 
    "Gardening", 
    "Building Traditional Structures", 
    "Artisan Crafting", 
    "Natural Fiber Weaving", 
    "Leather Tanning", 
    "Songwriting", 
    "Potluck Cooking", 
    "Conflict Resolution", 
    "Tool Maintenance", 
    "Sustainable Fishing", 
    "Ecotourism Management"
  ];
  